### ISSUE TITLE
Optimizer Test function error

### ISSUE THREAD

**Issue by jlardie** [FxnlBiomechLab/twsa-optimization-for-rra#2]
"Unrecognized function or variable 'body_mass'.

Error in rraTools.rrasetup/optimizeTrackingWeights (line 811)
                [i,S] = obj.executeRRAOptLoop(S,i,body_mass);

Error in runOptimizerHamner_Test (line 40)
        r.optimizeTrackingWeights('min_itrs',100,'max_itrs',200,'fcn_threshold',1)"

It looks as if the variable body_mass is being created in Line 781 of rrasetup.m however it isn't being passed forward to line 811, where the error is occurring. I believe I followed the instructions clearly. Using Matlab2021b and OpenSim 4.3 with latest MOCO configured. If any more info is needed, please just let me know. Thanks!

**Comment by RealSturdy** [comment]
Thanks! I will take a look at this section. I'm not sure if this code has been fully tested in OpenSim 4.3 yet, but there should be some updates coming soon.

**Comment by RealSturdy** [comment]
With recent code updates, the body_mass variable is no longer referenced. 

Current code tested in MATLAB R2020a with OpenSim 4.3. All example files run with no errors.
